export const ACTIONS = {
  ADD_DONATION: "ADD_DONATION",
  AUTH_USER: {
    START: "AUTH_USER.START",
    SUCCESS: "AUTH_USER.SUCCESS",
    FAILURE: "AUTH_USER.FAILURE"
  },
  CORE: {
    STARTUP: "CORE.STARTUP",
    FINISH: "CORE.FINISH"
  },
  FETCH_DONATIONS: {
    START: "FETCH_DONATIONS.START",
    SUCCESS: "FETCH_DONATIONS.SUCCESS",
    FAILURE: "FETCH_DONATIONS.FAILURE"
  },
  LOGIN_START: "LOGIN.START",
  UPDATE_ACCOUNT_TYPE: "UPDATE_ACCOUNT_TYPE"
};
